markdown: kramdown

title: "GDG Natal"
description: "Google Developer Group situado em Natal-RN Brasil"

permalink: /blog/:year/:month/:day/:title/
baseurl: ""

links:
  - title: Home
    url: /#home
  - title: Iniciativas
    url: /#iniciativas
  - title: Equipe
    url: /#equipe
  - title: Blog
    url: /Blog
  - title: Contato
    url: /#contato

url: "http://gdgnatal.com"
domain: "gdgnatal.com"

social:
  - desc: GOOGLE PLUS
    url: https://plus.google.com/+Gdgnatal-rn/ 
    title: Adicione no  google+
  - desc: GITHUB
    url:  https://github.com/gdg-natal
    title: Fork me on github
  - desc: FACEBOOK
    url:  https://facebook.com/gdgnatal
    title: Curta nossa página no Facebook
  - desc: GDG Natal Chapter
    url: https://developers.google.com/groups/chapter/111142392900301029730/
    title: Conheça nosso grupo

ga: UA-54337910-4

team:
  - name: Henri Cavalcante
    photo: https://avatars0.githubusercontent.com/u/2352034?v=3&s=460
    desc: Um desenvolvedor Full-stack que as vezes faz o papel de DevOps e que trabalha como CTO no wiquadro, mas verdade o que gosto mesmo é de fazer as coisas acontecerem e estar sempre me mantendo atualizado quando o assunto é tecnologia. #GetItDone
    facebook: http://fb.me/henricavalcante
    github: http://github.com/henricavalcante
    plus: https://plus.google.com/u/0/+HenriMichelCavalcante/
  - name: Hudson Brendon
    photo: https://avatars2.githubusercontent.com/u/5201888?v=3&s=460
    desc: Um Full Stack Developer, apaixonado por python e demais tecnologias que envolvem a linguagem, hardware aberto, devops e empreendedorismo.
    facebook: https://www.facebook.com/hudson.brendon
    github: https://github.com/hudsonbrendon
    plus: https://plus.google.com/u/0/116189383737787140965/
  - name: Jefferson Moura
    photo: /resources/imgs/organizers/jefferson.jpg
    desc: Front-end Developer, Auto-didata e palestrante, Fã do AngularJS, Hoje sou Front-end com foco em performance de dados e de layout, apaixonado por UI/UX estou sempre procurando métodos de melhorar a interface dos projetos.
    facebook: https://www.facebook.com/jeffersonmouraamador
    github: https://github.com/jeffersonmourak/
    plus: https://plus.google.com/+JeffersonMourak/

exclude: ['gruntfile.js', 'package.json', 'src', 'node_modules']
